fix: add support for multiple hostnames (#55)

diff --git a/install.yaml b/install.yaml
--- a/install.yaml
+++ b/install.yaml
@@ -1,8 +1,38 @@
 name: ddev-selenium-standalone-chrome
-pre_install_actions:
+
 project_files:
 - docker-compose.selenium-chrome.yaml
 - config.selenium-standalone-chrome.yaml
-global_files:
+
 post_install_actions:
-yaml_read_files:
+  - |
+    #ddev-nodisplay
+    #ddev-description:Checking docker-compose.selenium-chrome_extras.yaml for changes
+    if [ -f docker-compose.selenium-chrome_extras.yaml ] && ! grep -q '#ddev-generated' docker-compose.selenium-chrome_extras.yaml; then
+      echo "Existing docker-compose.selenium-chrome_extras.yaml does not have #ddev-generated, so can't be updated"
+      exit 2
+    fi
+  - |
+    #ddev-nodisplay
+    #ddev-description:Adding all hostnames to the selenium-chrome container to make them available
+    cat <<-END >docker-compose.selenium-chrome_extras.yaml
+    #ddev-generated
+    services:
+      selenium-chrome:
+        external_links:
+        {{- $selenium_chrome_hostnames := splitList "," (env "DDEV_HOSTNAME") -}}
+        {{- range $i, $n := $selenium_chrome_hostnames }}
+          - "ddev-router:{{- replace (env "DDEV_TLD") "\\${DDEV_TLD}" (replace (env "DDEV_PROJECT") "\\${DDEV_PROJECT}" $n) -}}"
+        {{- end }}
+    END
+removal_actions:
+  - |
+    #ddev-nodisplay
+    #ddev-description:Remove docker-compose.selenium-chrome_extras.yaml file
+    if [ -f docker-compose.selenium-chrome_extras.yaml ]; then
+      if grep -q '#ddev-generated' docker-compose.selenium-chrome_extras.yaml; then
+        rm -f docker-compose.selenium-chrome_extras.yaml
+      else
+        echo "Unwilling to remove '$DDEV_APPROOT/.ddev/docker-compose.selenium-chrome_extras.yaml' because it does not have #ddev-generated in it; you can manually delete it if it is safe to delete."
+      fi
+    fi
